name: Scala CI

on:
  [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Cache SBT and Ivy2 dependencies
          uses: actions/cache@v2
          with:
            path: |
              ~/.sbt
              ~/.ivy2
            key: ${{ runner.os }}-sbt-ivy-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/**') }}
            restore-keys: |
              ${{ runner.os }}-sbt-ivy-
      - name: Run tests
        run: sbt test